---
title: "About Me"
output:
  html_document:
    theme: "flatly"
---
I currently work in the Greetings Advanced Analytics & Data Science group at Hallmark Cards in Kansas City, MO. I primarily support the season cards product team in various analytics initiatives. Lately my work has involved a lot of time series forecasting and experimental design problems, and in my free time I've been playing with modeling with Gaussian processes and spatial statistics. I'm an avid R user, regular participant in the [Kansas City R user Meetup Group](https://www.meetup.com/Kansas-City-R-Users-Group/), and if you're in the area you should come too.

I'm formerly a graduate student in the Statistics Department at Iowa State University, where my M.S. creative component focused on Markov random fields and their application to spatial statistics. Before that, I graduated from the University of Kansas in 2016 with a B.S. in Mathematics and Economics, and I'm also a proud graduate of Newton High School in Newton, KS.

If you've made it this far you're almost certainly on your way out of this site. Here's some other more fun(?) places you can go on the internet and find me present:

-To my [LinkedIn](https://www.linkedin.com/in/steve-harms-ab46236b/)

-To my mostly empty [github](https://github.com/stharms)

-To what I'm [reading](https://www.goodreads.com/user/show/42417708-st-harms)

-To what I'm [listening to](https://www.albumoftheyear.org/user/stharms/)
